export const GET_SPORTS_REQUEST="GET_SPORTS_REQUEST"
export const GET_SPORTS_SUCCESS="GET_SPORTS_SUCCESS"
export const GET_SPORTS_FAILED="GET_SPORTS_FAILED"

export const GET_MOVIES_REQUEST="GET_MOVIES_REQUEST"
export const GET_MOVIES_SUCCESS="GET_MOVIES_SUCCESS"
export const GET_MOVIES_FAILED="GET_MOVIES_FAILED"

export const GET_MOVIEDETAILS_REQUEST="GET_MOVIEDETAILS_REQUEST"
export const GET_MOVIEDETAILS_SUCCESS="GET_MOVIEDETAILS_SUCCESS"
export const GET_MOVIEDETAILS_FAILED="GET_MOVIEDETAILS_FAILED"

export const GET_CELIBRITY_REQUEST="GET_CELIBRITY_REQUEST"
export const GET_CELIBRITY_SUCCESS="GET_CELIBRITY_SUCCESS"
export const GET_CELIBRITY_FAILED="GET_CELIBRITY_FAILED"

export const GET_GENERS_REQUEST="GET_GENERS_REQUEST"
export const GET_GENERS_SUCCESS="GET_GENERS_SUCCESS"
export const GET_GENERS_FAILED="GET_GENERS_FAILED"

export const GET_SPORTDETAILS_REQUEST="GET_SPORTDETAILS_REQUEST"
export const GET_SPORTDETAILS_SUCCESS="GET_SPORTDETAILS_SUCCESS"
export const GET_SPORTDETAILS_FAILED="GET_SPORTDETAILS_FAILED"

export const GET_SERIES_REQUEST="GET_SERIES_REQUEST"
export const GET_SERIES_SUCCESS="GET_SERIES_SUCCESS"
export const GET_SERIES_FAILED="GET_SERIES_FAILED"